### ISSUE TITLE
Using XFS file system

### ISSUE THREAD

**Issue by sachin-storehippo** [GoogleCloudPlatform/mongodb-cloud-manager#2]
Mongodb strongly recommends XFS file system for Wiretigered. 

https://docs.mongodb.com/manual/administration/production-notes/#platform-specific-considerations

What needs to be done to create instances that use XFS for persistent disks.

Thanks,

**Comment by manusis** [comment]
We need this feature. Is there any way we can have the support for this?

**Comment by crcsmnky** [comment]
Setting dynamically may or may not work so in the interim, look at [mongodb-instance-template.jinja#L68](https://github.com/GoogleCloudPlatform/mongodb-cloud-manager/blob/master/mongodb-instance-template.jinja#L68).

Specifically change the `mkfs.ext4` command to `mkfs.xfs` and update to the appropriate arguments for creating an XFS file system on the attached device.
